// <auto-generated />
using System;
using AspNetWebhookPublisher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetWebhookPublisher.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210105140555_Webhook")]
    partial class Webhook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookEvents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c358c09-d38b-4e8c-86b5-8597fee1a7e0"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 640, DateTimeKind.Local).AddTicks(2480),
                            Description = "Triggered when personel is created.",
                            DisplayName = "Person Created",
                            Name = "person.created"
                        },
                        new
                        {
                            Id = new Guid("70720dea-b4c1-4d49-bd40-fe9016b18d03"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 641, DateTimeKind.Local).AddTicks(9292),
                            Description = "Triggered when personel is updated.",
                            DisplayName = "Person Updated",
                            Name = "person.updated"
                        },
                        new
                        {
                            Id = new Guid("62a76f04-146a-419f-a785-71fc3e36ca8e"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 641, DateTimeKind.Local).AddTicks(9355),
                            Description = "Triggered when personel is deleted.",
                            DisplayName = "Person Deleted",
                            Name = "person.deleted"
                        });
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventId");

                    b.ToTable("WebhookPayloads");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<Guid>("WebhookPayloadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookPayloadId");

                    b.ToTable("WebhookResponses");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WebhookSubscriptionContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WebhookSubscriptionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookSubscriptionContentTypeId");

                    b.HasIndex("WebhookSubscriptionTypeId");

                    b.ToTable("WebhookSubscriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("468caa56-538f-4317-a5c7-cadcda765212"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 644, DateTimeKind.Local).AddTicks(8398),
                            IsActive = true,
                            PayloadUrl = "http://localhost:5040/webhook-json-data-test",
                            Secret = "secret",
                            WebhookSubscriptionContentTypeId = new Guid("4ad91b1a-4009-4620-a4b7-a17746e7bbf2"),
                            WebhookSubscriptionTypeId = new Guid("47d861e3-9042-4b65-b029-a5d07672abab")
                        },
                        new
                        {
                            Id = new Guid("3e93f47a-a422-4084-870c-667dc7196520"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 644, DateTimeKind.Local).AddTicks(9157),
                            IsActive = true,
                            PayloadUrl = "http://localhost:5040/webhook-form-data-test",
                            Secret = "secret",
                            WebhookSubscriptionContentTypeId = new Guid("845fe809-bacc-4aab-bdeb-6cb5e5b7292b"),
                            WebhookSubscriptionTypeId = new Guid("47d861e3-9042-4b65-b029-a5d07672abab")
                        });
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionAllowedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventId");

                    b.HasIndex("WebhookSubscriptionId");

                    b.ToTable("WebhookSubscriptionAllowedEvents");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptionContentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ad91b1a-4009-4620-a4b7-a17746e7bbf2"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 644, DateTimeKind.Local).AddTicks(444),
                            Name = "application/json"
                        },
                        new
                        {
                            Id = new Guid("845fe809-bacc-4aab-bdeb-6cb5e5b7292b"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 644, DateTimeKind.Local).AddTicks(470),
                            Name = "application/x-www-form-urlencoded"
                        });
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47d861e3-9042-4b65-b029-a5d07672abab"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 644, DateTimeKind.Local).AddTicks(2762),
                            Name = "All"
                        },
                        new
                        {
                            Id = new Guid("0c26be7d-8053-49e2-a590-ea991c1ae24a"),
                            Created = new DateTime(2021, 1, 5, 17, 5, 54, 644, DateTimeKind.Local).AddTicks(2781),
                            Name = "Specific"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookPayload", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookEvent", "WebhookEvent")
                        .WithMany()
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookEvent");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookResponse", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookPayload", "WebhookPayload")
                        .WithMany()
                        .HasForeignKey("WebhookPayloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookPayload");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscription", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookSubscriptionContentType", "WebhookSubscriptionContentType")
                        .WithMany()
                        .HasForeignKey("WebhookSubscriptionContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookSubscriptionType", "WebhookSubscriptionType")
                        .WithMany()
                        .HasForeignKey("WebhookSubscriptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookSubscriptionContentType");

                    b.Navigation("WebhookSubscriptionType");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionAllowedEvent", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookEvent", "WebhookEvent")
                        .WithMany()
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookSubscription", "WebhookSubscription")
                        .WithMany("WebhookSubscriptionAllowedEvents")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookEvent");

                    b.Navigation("WebhookSubscription");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscription", b =>
                {
                    b.Navigation("WebhookSubscriptionAllowedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
