// <auto-generated />
using System;
using AspNetWebhookPublisher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetWebhookPublisher.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210105132832_Webhook")]
    partial class Webhook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookEvents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2207623-81c1-4964-ab7a-0d47d1f0b1c6"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 41, DateTimeKind.Local).AddTicks(6621),
                            Description = "Triggered when personel is created.",
                            DisplayName = "Person Created",
                            Name = "person.created"
                        },
                        new
                        {
                            Id = new Guid("6fdc0abb-847d-4ebd-b4b1-7ec6cbf07fe5"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 42, DateTimeKind.Local).AddTicks(2797),
                            Description = "Triggered when personel is updated.",
                            DisplayName = "Person Updated",
                            Name = "person.updated"
                        },
                        new
                        {
                            Id = new Guid("e95c84d1-bde4-455e-934c-23203a9085db"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 42, DateTimeKind.Local).AddTicks(2810),
                            Description = "Triggered when personel is deleted.",
                            DisplayName = "Person Deleted",
                            Name = "person.deleted"
                        });
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventId");

                    b.ToTable("WebhookPayloads");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<Guid>("WebhookPayloadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookPayloadId");

                    b.ToTable("WebhookResponses");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WebhookSubscriptionContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WebhookSubscriptionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookSubscriptionContentTypeId");

                    b.HasIndex("WebhookSubscriptionTypeId");

                    b.ToTable("WebhookSubscriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("495b762c-d088-47ab-a8f2-aa43c783fc39"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 43, DateTimeKind.Local).AddTicks(3963),
                            IsActive = true,
                            PayloadUrl = "http://localhost:5040/webhook-form-data-test",
                            Secret = "secret",
                            WebhookSubscriptionContentTypeId = new Guid("bc71a96a-50fe-4da8-9b6c-4c3d648ba65f"),
                            WebhookSubscriptionTypeId = new Guid("d8d11b47-a78f-40aa-adf9-8f0b7475e4e1")
                        },
                        new
                        {
                            Id = new Guid("c49cd2ef-89d0-4f31-b0c1-8d8d7f9a5fbb"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 43, DateTimeKind.Local).AddTicks(4257),
                            IsActive = true,
                            PayloadUrl = "http://localhost:5040/webhook-json-data-test",
                            Secret = "secret",
                            WebhookSubscriptionContentTypeId = new Guid("4f8698fa-fd8f-487f-82d2-2887754fa9fd"),
                            WebhookSubscriptionTypeId = new Guid("d8d11b47-a78f-40aa-adf9-8f0b7475e4e1")
                        });
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionAllowedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventId");

                    b.HasIndex("WebhookSubscriptionId");

                    b.ToTable("WebhookSubscriptionAllowedEvents");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptionContentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc71a96a-50fe-4da8-9b6c-4c3d648ba65f"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 43, DateTimeKind.Local).AddTicks(927),
                            Name = "application/json"
                        },
                        new
                        {
                            Id = new Guid("4f8698fa-fd8f-487f-82d2-2887754fa9fd"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 43, DateTimeKind.Local).AddTicks(937),
                            Name = "application/x-www-form-urlencoded"
                        });
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8d11b47-a78f-40aa-adf9-8f0b7475e4e1"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 43, DateTimeKind.Local).AddTicks(1800),
                            Name = "All"
                        },
                        new
                        {
                            Id = new Guid("8a684a84-fd72-47b2-ac97-20713b8d1c64"),
                            Created = new DateTime(2021, 1, 5, 16, 28, 32, 43, DateTimeKind.Local).AddTicks(1816),
                            Name = "Specific"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookPayload", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookEvent", "WebhookEvent")
                        .WithMany()
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookEvent");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookResponse", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookPayload", "WebhookPayload")
                        .WithMany()
                        .HasForeignKey("WebhookPayloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookPayload");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscription", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookSubscriptionContentType", "WebhookSubscriptionContentType")
                        .WithMany()
                        .HasForeignKey("WebhookSubscriptionContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookSubscriptionType", "WebhookSubscriptionType")
                        .WithMany()
                        .HasForeignKey("WebhookSubscriptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookSubscriptionContentType");

                    b.Navigation("WebhookSubscriptionType");
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscriptionAllowedEvent", b =>
                {
                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookEvent", "WebhookEvent")
                        .WithMany()
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetWebhookPublisher.Entities.WebhookSubscription", "WebhookSubscription")
                        .WithMany("WebhookSubscriptionAllowedEvents")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookEvent");

                    b.Navigation("WebhookSubscription");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetWebhookPublisher.Entities.WebhookSubscription", b =>
                {
                    b.Navigation("WebhookSubscriptionAllowedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
